import React from 'react'
import { graphql } from 'gatsby'
import Layout from '../components/layout'
import SEO from '../components/seo'

const About = ({ data }) => (
  <Layout>
    <SEO title="About that dog" />
    <h1>About that dog</h1>
    <p>It was so nice</p>
    <p>
      This part is generated by a query of the site title:{' '}
      <code>{data.site.siteMetadata.title}</code>
    </p>
    <p>
      Here is the description from the config file:
      <code>{data.site.siteMetadata.description}</code>
    </p>
  </Layout>
)

export default About

export const query = graphql`
  query {
    site {
      siteMetadata {
        title
        description
      }
    }
  }
`
